import os
import smtplib
import time
import requests
import urllib.parse
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# ---- CHROME SETUP ----
chrome_options = Options()
chrome_options.add_argument("headless")
chrome_options.add_argument("no-sandbox")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
time.sleep(1)

# ---- FILTERS ----
TECHNICAL_ROLES = [
    "data scientist", "data science", "data analyst", "machine learning", "ml", "ai",
    "python", "django", "flask", "full stack", "react", "angular", "vue", "javascript",
    "typescript", "intern", "trainee", "developer", "engineer"
]
EXCLUDE_ROLES = ["php", "laravel", "wordpress", "drupal", ".net", "c#", "java", "spring", "hibernate"]

# ---- SCRAPE INFOPARK ----
def fetch_infopark_jobs():
    jobs = []
    for page in range(1, 3):
        url = f"https://infopark.in/companies/job-search?page={page}"
        driver.get(url)
        soup = BeautifulSoup(driver.page_source, "html.parser")
        rows = soup.select("table tr")[1:]
        for row in rows:
            cols = row.find_all("td")
            if len(cols) < 3:
                continue
            title = cols[1].text.strip()
            company = cols[2].text.strip()
            link_el = row.find("a", href=True)
            job_link = link_el["href"] if link_el else ""
            if not job_link.startswith("http"):
                job_link = "https://infopark.in" + job_link
            if any(ex in title.lower() for ex in EXCLUDE_ROLES):
                continue
            if any(role in title.lower() for role in TECHNICAL_ROLES):
                jobs.append({"title": title, "company": company, "link": job_link})
    return jobs

# ---- EMAIL ----
def send_email(jobs):
    sender = os.getenv("EMAIL_USER")
    password = os.getenv("EMAIL_PASS")
    recipients = [x.strip() for x in os.getenv("EMAIL_TO", "").split(",") if x.strip()]
    tracker_url = os.getenv("TRACKER_URL")  # your Google Apps Script exec link

    subject = f"🌟 Latest Kerala IT Park Jobs – {datetime.now().strftime('%d %b %Y')}"

    for student_email in recipients:
        html = """
        <html>
        <body style="font-family:Arial;background:#f4f8f5;padding:20px;">
        <div style="background:#007A33;padding:15px;border-radius:12px;color:white;text-align:center;">
            <h2>Maitexa Technologies Pvt Ltd</h2>
            <p>Integrating Minds | 4437, First Floor, AVS Tower, Opp. Jayalakshmi Silks, Kallai Road, Calicut,673002, Kerala</p>
        </div><br>
        <p>Dear <b>{email}</b>,</p>
        <p>Here are the latest <b>Kerala IT Park openings</b> for you:</p>
        """.format(email=student_email)

        for job in jobs:
            safe_link = urllib.parse.quote(job['link'], safe='')
            safe_title = urllib.parse.quote(job['title'], safe='')
            safe_email = urllib.parse.quote(student_email, safe='')

            tracking_link = f"{tracker_url}?email={safe_email}&job={safe_title}&link={safe_link}"

            html += f"""
            <div style="border:1px solid #ccc;border-radius:10px;padding:12px;margin-bottom:12px;background:white;">
                <h3 style="color:#007A33;margin:0;">{job['title']}</h3>
                <p>🏢 {job['company']}</p>
                <a href="{tracking_link}" style="display:inline-block;background:#007A33;color:white;padding:8px 14px;text-decoration:none;border-radius:6px;">View & Apply</a>
            </div>
            """

        html += "<p style='font-size:12px;color:#777;'>Generated by Maitexa Job Tracker © 2025</p></body></html>"

        msg = MIMEMultipart("alternative")
        msg["From"] = sender
        msg["To"] = student_email
        msg["Subject"] = subject
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)

        print(f"✅ Email sent to: {student_email}")

# ---- MAIN ----
if __name__ == "__main__":
    jobs = fetch_infopark_jobs()
    driver.quit()
    if jobs:
        send_email(jobs)
    else:
        print("⚠️ No matching jobs found.")
